// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/home/riccardo/Documenti/GeantProjects/LEM_simulation/ROOTNotebook/../ROOT_macros/GeometricalFactor.C";

#endif
