# ---------------------------------------------------------------------------- #
#                    GENERAL PARTICLE SOURCE DEFAULT CONFIOG                   #
# ---------------------------------------------------------------------------- #

/particleEnergyRandom/DebbuggingModeIsOn false
/gps/verbose 0
/gps/pos/type Plane
#/gps/pos/shape Square
/gps/pos/shape Circle

/gps/pos/centre 0 0 -3.3 cm
#/gps/pos/halfx 2.0 cm
#/gps/pos/halfy 2.0 cm

/gps/pos/radius 1.8 cm

/gps/ang/type iso
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ang/maxtheta 90 deg
/gps/ang/mintheta 0 deg

/gps/particle e-
/gps/ene/min 0.001 MeV
/gps/ene/max 7 MeV

# ---------------------------------------------------------------------------- #
#                    PARTICLE GUN FOR DEBUGGING MODE CONFIOG                   #
# ---------------------------------------------------------------------------- #

/gun/particle e-
/particleEnergyRandom/Ek_min 0.1
/particleEnergyRandom/Ek_max 0.7
/particleEnergyRandom/DebbuggingModeIsOn false

# ---------------------------------------------------------------------------- #
#                       DEFAULT FILE NAME FOR SAVING DATA                      #
# ---------------------------------------------------------------------------- #
/NameOfFile/NameOfFile ProvaFile.root


