# ---------------------------------------------------------------------------- #
#                                SIMULATION RUN                                #
# ---------------------------------------------------------------------------- #
#
# - No debugging mode (random)
# - Isotropic flux generation from a surface
# - Electrons protons alpha muons
# - Fine tuning for acceptance at low energies
# - energy spectrum flat
#
#

/particleEnergyRandom/DebbuggingModeIsOn true

/gps/verbose 0
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 0 0 -3.4 cm
/gps/pos/halfx 2.0 cm
/gps/pos/halfy 2.0 cm
/gps/ang/type iso
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ang/maxtheta 90 deg
/gps/ang/mintheta 0 deg

 # ---------------------------------------------------------------------------- #
 #                                   ELECTRONS                                  #
 # ---------------------------------------------------------------------------- #

/gun/particle e-
/particleEnergyRandom/Ek_min 0.01 MeV
/particleEnergyRandom/Ek_max 7 MeV

/NameOfFile/NameOfFile ../DST_E_05022023/05_02_2023_ELECTRON
/run/beamOn 1000000

 # ---------------------------------------------------------------------------- #
 #                                    PROTONS                                   #
 # ---------------------------------------------------------------------------- #

/gun/particle proton
/particleEnergyRandom/Ek_min 0.1 MeV
/particleEnergyRandom/Ek_max 30 MeV


/NameOfFile/NameOfFile ../DST_E_05022023/05_02_2023_PROTON
/run/beamOn 1000000

 # ---------------------------------------------------------------------------- #
 #                                     ALPHA                                    #
 # ---------------------------------------------------------------------------- #

/gun/particle alpha
/particleEnergyRandom/Ek_min 1 MeV
/particleEnergyRandom/Ek_max 100 MeV

/NameOfFile/NameOfFile ../DST_E_05022023/05_02_2023_ALPHA
/run/beamOn 1000000