# ---------------------------------------------------------------------------- #
#                                SIMULATION RUN                                #
# ---------------------------------------------------------------------------- #
#
# - YES debugging mode (random)
# - Fixed directions
# - Electrons protons alpha muons
#
# - energy spectrum flat
#
#

/particleEnergyRandom/DebbuggingModeIsOn true

/gps/verbose 0
/gps/pos/type Plane
/gps/pos/shape Square
/gps/pos/centre 0 0 -2.4 cm
/gps/pos/halfx 11.5 cm
/gps/pos/halfy 11.5 cm
/gps/ang/type iso
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ang/maxtheta 90 deg
/gps/ang/mintheta 0 deg


 # ---------------------------------------------------------------------------- #
 #                                   ELECTRONS                                  #
 # ---------------------------------------------------------------------------- #

/gun/particle e-
/particleEnergyRandom/Ek_min 0.0001
/particleEnergyRandom/Ek_max 11

/NameOfFile/NameOfFile Edep_05_08_2022_ELECTRON
/run/beamOn 1000000

 # ---------------------------------------------------------------------------- #
 #                                    PROTONS                                   #
 # ---------------------------------------------------------------------------- #

/gun/particle proton
/particleEnergyRandom/Ek_min 0.01
/particleEnergyRandom/Ek_max 300

/NameOfFile/NameOfFile Edep_05_08_2022_PROTON
/run/beamOn 1000000

 # ---------------------------------------------------------------------------- #
 #                                     ALPHA                                    #
 # ---------------------------------------------------------------------------- #


/gun/particle alpha
/particleEnergyRandom/Ek_min 0.01
/particleEnergyRandom/Ek_max 500

/NameOfFile/NameOfFile Edep_05_08_2022_ALPHA
/run/beamOn 1000000

 # ---------------------------------------------------------------------------- #
 #                                     MUONS                                    #
 # ---------------------------------------------------------------------------- #


/gun/particle mu-
/particleEnergyRandom/Ek_min 10000
/particleEnergyRandom/Ek_max 100000

/NameOfFile/NameOfFile Edep_05_08_2022_MUON
/run/beamOn 1000000