# ---------------------------------------------------------------------------- #
#                             RUN DEBUG 19 12 2022                             #
# ---------------------------------------------------------------------------- #
# electroms alpha and protons


/particleEnergyRandom/DebbuggingModeIsOn true
/particleEnergyRandom/IsExponential true

# --------------------------------- ELECTRON --------------------------------- #

/gun/particle e-
/particleEnergyRandom/Ek_min 0.08
/particleEnergyRandom/Ek_max 10.0
/NameOfFile/NameOfFile ELECTRON_19122022
/run/beamOn 10000000


# ----------------------------------- PROTON --------------------------------- #

/gun/particle proton
/particleEnergyRandom/Ek_min 3.
/particleEnergyRandom/Ek_max 100.0
/NameOfFile/NameOfFile PROTON_19122022
/run/beamOn 10000000


# ----------------------------------- ALPHA ---------------------------------- #

/gun/particle alpha
/particleEnergyRandom/Ek_min 10.
/particleEnergyRandom/Ek_max 320.0
/NameOfFile/NameOfFile ALPHA_19122022
/run/beamOn 10000000
