# ---------------------------------------------------------------------------- #
#                                SIMULATION RUN                                #
# ---------------------------------------------------------------------------- #
#
# - No debugging mode (random)
# - Isotropic flux generation from a surface
# - Electrons protons alpha muons
# - Fine tuning for acceptance at low energies
# - energy spectrum flat
#
#

/particleEnergyRandom/DebbuggingModeIsOn false

/gps/verbose 0
/gps/pos/type Plane
#/gps/pos/shape Square
/gps/pos/shape Circle

/gps/pos/centre 0 0 -3.3 cm
#/gps/pos/halfx 2.0 cm
#/gps/pos/halfy 2.0 cm

/gps/pos/radius 1.8 cm

/gps/ang/type iso
/gps/ene/type Lin
/gps/ene/gradient 0
/gps/ene/intercept 1
/gps/ang/maxtheta 90 deg
/gps/ang/mintheta 0 deg

 # ---------------------------------------------------------------------------- #
 #                                   ELECTRONS                                  #
 # ---------------------------------------------------------------------------- #

/gps/particle e-
/gps/ene/min 0.001 MeV
/gps/ene/max 7 MeV

/NameOfFile/NameOfFile ../DST_20022023/20_02_2023_ELECTRON
/run/beamOn 10000000

 # ---------------------------------------------------------------------------- #
 #                                    PROTONS                                   #
 # ---------------------------------------------------------------------------- #

/gps/particle proton
/gps/ene/min 0.01 MeV
/gps/ene/max 90 MeV

/NameOfFile/NameOfFile ../DST_20022023/20_02_2023_PROTON
/run/beamOn 10000000

 # ---------------------------------------------------------------------------- #
 #                                     ALPHA                                    #
 # ---------------------------------------------------------------------------- #

/gps/particle alpha
/gps/ene/min 0.01 MeV
/gps/ene/max 300 MeV

/NameOfFile/NameOfFile ../DST_20022023/20_02_2023_ALPHA
/run/beamOn 10000000